version: '3.9'

services:
  web:
    image: nginx:1.21-alpine
    container_name: skeleton-web-container
    volumes:
      - .:/var/www/html/
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - '8080:80'

  php:
    build: ./docker/php
    container_name: skeleton-php-container
    volumes:
      - .:/var/www/html/

  db:
    image: mysql:8.0-debian
    container_name: skeleton-db-container
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main